#!/bin/sh

name="climasense-edge"
pidfile="/run/$name.pid"
command="/usr/bin/joss"
working_dir="/opt/climasense/edge"

case "$1" in
  start)
    [ -f /data/climasense/.env ] || { echo "ClimaSense: falta /data/climasense/.env"; exit 1; }
    echo "Starting $name"
    cd "$working_dir"
    start-stop-daemon -S -b -m -p "$pidfile" -c climasense:climasense -x "$command" -- run main.joss
    ;;
  stop)
    echo "Stopping $name"
    start-stop-daemon -K -p "$pidfile" -R TERM/10/KILL/5 || true
    rm -f "$pidfile"
    ;;
  restart)
    "$0" stop
    "$0" start
    ;;
  status)
    start-stop-daemon -K -t -p "$pidfile"
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac
